name: test_task_audety
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.4.0
  get_it: ^7.6.7
  go_router: ^13.1.0
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  responsive_sizer: ^3.3.0+1
  widget_zoom: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env/app_keys.json